export const NOTIFICATION_TYPES = {
  APPLICATION: "APPLICATION",
  SHORTLISTED: "SHORTLISTED",
  INTERVIEW: "INTERVIEW",
  SELECTED: "SELECTED",
  REJECTED: "REJECTED",
  JOB: "JOB",
  SYSTEM: "SYSTEM",
};
